//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelMVCUI.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public int Id { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<short> Salary { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public bool Gender { get; set; }
        public bool Married { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
